### ISSUE TITLE
Wrong stride

### ISSUE THREAD

**Issue by ghost** [rupertnash/ndarray#1]
Hi @rupertnash, I think there is a small typo in the accumulated stride equation that breaks the logic: https://github.com/rupertnash/ndarray/blob/main/include/rwn/ndarray.hpp#L35
Where reads
`m_strides[i] = m_strides[i + i] * m_dims[i + 1];` 
Should be
 `m_strides[i] = m_strides[i + 1] * m_dims[i + 1];`

When do you advice to use this class?, I am doing a performance test with a simple assignment in a loop (see below), and I get: 

- `double** ras`  = 0.26 s
- `std::vector<std::vector<double>> vect` = 0.46 s
- `ndarray nd` = 1.42 s.  

I guess it is good in some cases for convenience (to avoid leaking)  like we do in VESTEC, but what would be the gain with respect to using a std::vector? Maybe the fact that the data is stored in a unique array so it may be good for MPI communications? Thanks, cool code, it really took me a while to just to understand the logic!!!! :DDD

```
#include <chrono>
#include <iostream>
#include "ndarray.hpp"
#include <vector>

template <class T> T** Ras(int nrow, int ncol) {
    T** ras = new T * [nrow];
    for (int ii = 0; ii < nrow; ii++) {
        ras[ii] = new T[ncol];
    }
    return ras;
}

using namespace rwn;
int main()
{
    int nrow = 15000;
    int ncol = 15000;
    auto ras = Ras<double>(nrow, ncol);
    ndarray<double, 2> nd = ndarray<double, 2> { {nrow,ncol} , 0.0 };
    std::vector <std::vector<double> > vect(nrow, std::vector<double>(ncol, 1));

    for (size_t ii = 0; ii < nrow; ii++)
    {
        for (size_t jj = 0; jj < ncol; jj++)
        {
            ras[ii][jj]= ii * ncol + jj;
            nd(ii, jj) = ii * ncol + jj;
            vect[ii][jj] = ii * ncol + jj;
        }
    }
   
   auto start = std::chrono::high_resolution_clock::now();
   for (size_t ii = 0; ii < nrow; ii++)
    {
        for (size_t jj = 0; jj < ncol; jj++)
        {
            nd(ii, jj) =0.1* nd(ii, jj);
            nd(ii, jj) = 0.2 * nd(ii, jj);
        }
    }
   auto finish = std::chrono::high_resolution_clock::now();
   std::chrono::duration<double> elapsed = finish - start;
   std::cout << "ndarray : " << elapsed.count() << " s\n";

   start = std::chrono::high_resolution_clock::now();
   for (size_t ii = 0; ii < nrow; ii++)
   {
       for (size_t jj = 0; jj < ncol; jj++)
       {
           ras[ii][jj] =0.1* ras[ii][jj];
           ras[ii][jj] = 0.2 * ras[ii][jj];
       }
   }
   finish = std::chrono::high_resolution_clock::now();
   elapsed = finish - start;
   std::cout << "pointers :" << elapsed.count() << " s\n";


   start = std::chrono::high_resolution_clock::now();
   for (size_t ii = 0; ii < nrow; ii++)
   {
       for (size_t jj = 0; jj < ncol; jj++)
       {
           vect[ii][jj] = 0.1 * vect[ii][jj];
           vect[ii][jj] = 0.2 * vect[ii][jj];
       }
   }
   finish = std::chrono::high_resolution_clock::now();
   elapsed = finish - start;
   std::cout << "vectors :" << elapsed.count() << " s\n";
```

**Comment by rupertnash** [comment]
Hi Santi - thanks for spotting the bug! Much appreciated!

I just compiled and ran your benchmark. I get:
```
ndarray : 0.235468 s
pointers :0.59562 s
vectors :0.28573 s
```
Which is roughly what I'd expect. (Although I would have guessed that vectors and pointers would be closer together).

Did you turn on optimisation?

**Comment by ghost** [comment]
Hi Rupe, I am using VS2019 on release with the following optimization
```
- /O2 =Maximum Optimization (favor speed)
- /Oi = Enable intrinsic function
- /Ot = Favor fast code
- /GL =  whole program optimization
```
I am also trying on linux  using g++ and a slightly different code:
-O1
```
ndarray : 6.81094 s
pointers :2.00856 s
vectors :2.88564 s
```
-O2 :
```
ndarray : 2.00138 s
pointers :1.9692 s
vectors :1.97921 s
```
-O3:
```
ndarray : 1.20994 s
pointers :1.1945 s
vectors :1.20758 s
```
it is surprising that you basically get the opposite results that I get on VS with pointers being the slowest by far, and that in this benchmark they all seem really equivalent (!?!)

**Comment by rupertnash** [comment]
The surprise is that MSVC is giving bad performance. The memory access patterns are much better for ndarray: that has a single contiguous block traversed in order vs. one block per row (while each block is contig. and traversed in order, each row is likely to result in a cache miss). The surprise is that vector is much better than Ras/pointer since they are very similar from a memory perspective.

I figured the likely cause was failure to vectorise, so used compiler explorer: https://godbolt.org/z/89q5bzTsE

It says "info C5002: loop not vectorized due to reason '501'" , which MS says means "Induction variable isn't local; or upper bound isn't loop-invariant."

This statement is false (the var is local and loop invariant), so this is a compiler problem.

Since windows is irrelevant for HPC, I'm closing this.
